name: C/C++ CI

on:
  push:
    branches:
      - master
      - dashing-devel
  pull_request:
    branches:
      - master
      - dashing-devel

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:eloquent
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: colcon build
    - name: test
      run: colcon test
    - name: test results
      run: colcon test-results
